AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Local Debug Stack (Points to Dist)

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 20
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: "monorepo-local"
        IS_OFFLINE: "true"
        AWS_SAM_LOCAL: "true"

Resources:
  # ============================================================
  # 1. SHARED RESOURCES (DynamoDB)
  # ============================================================
  AuditTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: product-audit-trail-local
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  # ============================================================
  # 2. PRICE FETCHER
  # ============================================================
  PriceFetcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Points to the built code
      CodeUri: ../dist
      Handler: functions/price-fetcher/src/handler.handler
      
      Architectures:
        - x86_64
      
      Environment:
        Variables:
          AUDIT_TABLE_NAME: !Ref AuditTable
          ORACLE_CONN_STRING: "oracle-local:1521/FREEPDB1"
          DYNAMODB_ENDPOINT: "http://dynamodb-local:8000"
      
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditTable

      # The API Gateway Trigger
      # Without this, 'sam local start-api' doesn't know what URL maps to this lambda
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /product
            Method: ANY